// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqbfkxstncplnyhawtuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxYmZreHN0bmNwbG55aGF3dHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTEwNjQsImV4cCI6MjA2MDk2NzA2NH0.iujs6A5fcC5zhbJKuN5oEb0Z0-L66NMk9ERnwCdX-54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);